apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: haproxy-fic
  name: haproxy-fed-ingress-controller
  namespace: federation-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: haproxy-fic
      name: haproxy-fed-ingress-controller
    spec:
      containers:
      - env:
        - name: KUBECONFIG
          value: /etc/federation/controller-manager/config
        image: docker.io/vinhags/federated-haproxy-ingress-controller:v0.0.1-prealpha
        imagePullPolicy: Always
        name: controller-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/federation/controller-manager
          name: fed-controller-manager-kubeconfig
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: federation-controller-manager
      serviceAccountName: federation-controller-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fed-controller-manager-kubeconfig
        secret:
          defaultMode: 420
          secretName: fed-controller-manager-kubeconfig

